"""Write THIRD_PARTY_NOTICES.md for this repository's shipped Python build.

Plan Phase 6 step 5. Run it in the build environment (CI or the Docker
build), after the package and its runtime extras are installed:

    pip install pip-licenses
    python scripts/third_party_notices.py

The file lists the licence of every installed Python package (pip-licenses,
licenses.xlsx L101) and, when mantau-AI's `mantau` package is installed,
appends its notices for the packaged models and their training data
(`mantau/THIRD_PARTY_NOTICES.md`: MediaPipe, the dataset attributions that
CC BY and GMDCSA24 require).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from importlib import resources
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OWN_PACKAGES = ("pip-licenses", "prettytable", "wcwidth", "pip", "setuptools", "wheel")


def package_section() -> str:
    result = subprocess.run(
        [sys.executable, "-m", "piplicenses", "--format=markdown", "--with-urls",
         "--with-license-file", "--no-license-path", "--order=name",
         "--ignore-packages", *OWN_PACKAGES],
        capture_output=True, text=True, check=True)
    return "## Python packages\n\n" + result.stdout.strip() + "\n"


def model_section() -> str | None:
    try:
        notice = resources.files("mantau").joinpath("THIRD_PARTY_NOTICES.md")
        text = notice.read_text(encoding="utf-8")
    except (ModuleNotFoundError, FileNotFoundError):
        return None
    # Nest mantau-AI's headings one level below ours.
    return "\n".join("#" + line if line.startswith("#") else line
                     for line in text.splitlines()) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=REPO / "THIRD_PARTY_NOTICES.md")
    args = parser.parse_args(argv)
    parts = ["# Third-party notices\n\nGenerated by `scripts/third_party_notices.py` at build "
             "time; do not edit by hand.\n", package_section()]
    models = model_section()
    if models is not None:
        parts.append(models)
    args.out.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
